plugins { id 'com.android.application' }

android {
    namespace 'josh.policy'
    compileSdk 35

    defaultConfig {
        applicationId "josh.policy"
        minSdk 31
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("../dpc.jks")
            storePassword "jesus319"
            keyAlias "dpc"
            keyPassword "jesus319"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
